### ISSUE TITLE
This is an exception to test if the integration with Flare works.

### ISSUE THREAD

**Issue by freekmurze** [freekmurze/stream-test#2]
**`Exception`**

Facade\Ignition\Commands\TestCommand::sendTestException
```php
71       protected function sendTestException()
72       {
73*          $testException = new Exception('This is an exception to test if the integration with Flare works.');
74   
75           try {
```
*File: /Users/freek/dev/code/freek.dev/vendor/facade/ignition/src/Commands/TestCommand.php*

[Open in Flare](https://flareapp.io/errors/467554/latest)

**Comment by rubenvanassche** [comment]
I've fixed this!
